#!/bin/bash

# Simple runnable shell script to avoid the manual work
# This script runs the plotter code, gets the c++ outut
# compiles  it  and executes its output(which generates
# the svg). This is then renamed, & temp files are
# removed

# 1st arg - input .plt file

f=$1
l=${#f} 

file=${f::l-4}

#attach the libraries
python incLib.py $1

./plotter < $1 > $file.cpp

g++ -std=c++11 $file.cpp

./a.out

mv hello.svg $file.svg

#reset the file to normal
mv $file.plt_tmp $file.plt

#remove the cpp and out files
rm $file.cpp a.out
